# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib BayesSEIR, .registration = TRUE
#' @importFrom Rcpp evalCpp
getS <- function(S0, Estar) {
    .Call('_BayesSEIR_getS', PACKAGE = 'BayesSEIR', S0, Estar)
}

#' @useDynLib BayesSEIR, .registration = TRUE
#' @importFrom Rcpp evalCpp
getE <- function(E0, Estar, Istar) {
    .Call('_BayesSEIR_getE', PACKAGE = 'BayesSEIR', E0, Estar, Istar)
}

#' @useDynLib BayesSEIR, .registration = TRUE
#' @importFrom Rcpp evalCpp
getI <- function(I0, Istar, Rstar) {
    .Call('_BayesSEIR_getI', PACKAGE = 'BayesSEIR', I0, Istar, Rstar)
}

#' @useDynLib BayesSEIR, .registration = TRUE
#' @importFrom Rcpp evalCpp
colByVec <- function(x, y) {
    .Call('_BayesSEIR_colByVec', PACKAGE = 'BayesSEIR', x, y)
}

